name: TransLite
options:
  bundleIdPrefix: com.translite
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

packages:
  Sparkle:
    url: https://github.com/sparkle-project/Sparkle
    from: "2.5.0"

settings:
  base:
    MARKETING_VERSION: "1.0.2"
    CURRENT_PROJECT_VERSION: "3"
    SWIFT_VERSION: "5.9"
    CODE_SIGN_STYLE: Manual
    CODE_SIGN_IDENTITY: "0FCEEAA4861A3809015D60D8BD083B396BD79016"
    DEVELOPMENT_TEAM: 2DBHSD6G6F
    ENABLE_HARDENED_RUNTIME: YES

targets:
  TransLite:
    type: application
    platform: macOS
    sources:
      - path: TransLite
        excludes:
          - "**/*.entitlements"
    dependencies:
      - package: Sparkle
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.translite.app
        INFOPLIST_FILE: TransLite/Info.plist
        CODE_SIGN_ENTITLEMENTS: TransLite/TransLite.entitlements
        PRODUCT_NAME: TransLite
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        COMBINE_HIDPI_IMAGES: YES
        LD_RUNPATH_SEARCH_PATHS:
          - $(inherited)
          - "@executable_path/../Frameworks"
