name: TransLite
options:
  bundleIdPrefix: com.translite
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.9"
    CODE_SIGN_STYLE: Manual
    CODE_SIGN_IDENTITY: "-"
    ENABLE_HARDENED_RUNTIME: NO

targets:
  TransLite:
    type: application
    platform: macOS
    sources:
      - path: TransLite
        excludes:
          - "**/*.entitlements"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.translite.app
        INFOPLIST_FILE: TransLite/Info.plist
        CODE_SIGN_ENTITLEMENTS: TransLite/TransLite.entitlements
        PRODUCT_NAME: TransLite
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        COMBINE_HIDPI_IMAGES: YES
        LD_RUNPATH_SEARCH_PATHS:
          - $(inherited)
          - "@executable_path/../Frameworks"
